# formatters.tcl --
#
# formatters run within the template namespace and provide template
# specific formatting of data

source ~/Tcl/htmlrep.tcl

package require ngis::hrformat
package require ngis::trimmers

variable hr_formatter

set hr_formatter [::ngis::HRFormat create [::ngis::Formatters new_cmd hr]]
::oo::objdefine $hr_formatter {mixin ::ngis::HTMLTrimmer}

proc entities_table {rows_l} {
    variable hr_formatter

    #set out "<pre>"
    #foreach r $rows_l {
    #    lassign $r gid descr uri
    #
    #    set uri_d [uri::split $uri]
    #
    #    set host ""
    #    if {[dict exists $uri_d host]} {
    #        set host [::rivet::xml [dict get $uri_d host] [list a href $uri]]
    #    }

    #    if {[string length $descr] > 80} {
    #        set descr "[string range $descr 0 76]..."
    #    }
    #    append out [format "%4s %80s %25s\n" $gid $descr $host]
    #}
    #append out "</pre>"
    #return $out

    return [$hr_formatter c108 $rows_l]
}

# service_table --
#
# print a table of a service data. Argument is a dictionary
# of service data generated by procedure ::ngis::service::service_data
#

proc service_table {service_d} {
    set service_report [::report::report service_report 2 style simpletable]
}
