package ifneeded ngis::readconf           1.0 [list source [file join $dir generic readconf.tcl]]
package ifneeded ngis::configuration      2.1 [list source [file join $dir ngis_conf.tcl]]
package ifneeded safelock                 1.0 [list source [file join $dir generic safelock.tcl]]
package ifneeded ngis::logger             0.1 [list source [file join $dir generic logger.tcl]]
package ifneeded ngis::roothandler        1.0 [list source [file join $dir handlers root_handler.tcl]]
package ifneeded ngis::login              1.0 [list source [file join $dir handlers login.tcl]]
package ifneeded ngis::page               1.0 [list source [file join $dir tcl snigpage.tcl]]
package ifneeded snig::page               1.0 [list source [file join $dir pages snigpage.tcl]]
package ifneeded snigreport	   			  0.6 [list source [file join $dir utils report.tcl]]
package ifneeded struct::snigmatrix       2.3 [list source [file join $dir utils matrix.tcl]]
package ifneeded ngis::trimmers           0.1 [list source [file join $dir utils trimmers.tcl]]
#package ifneeded ngis::fetch_tasks       1.0 [list source [file join $dir utils fetch_registered_tasks.tcl]]
package ifneeded ngis::ancillary_io_thread 1.0 [list source [file join $dir generic ancillary_io_thread.tcl]]
package ifneeded ngis::ancillary_io       1.0 [list source [file join $dir generic ancillary_io.tcl]]
package ifneeded ngis::webservice         1.0 [list source [file join $dir tcl snig_wsservice.tcl]]
package ifneeded ngis::content_fence      1.0 [list source [file join $dir handlers static_content_fence.tcl]]
package ifneeded ngis::users              1.0 [list source [file join $dir handlers users.tcl]]
package ifneeded ngis::entityhandler      1.1 [list source [file join $dir handlers entity.tcl]]
package ifneeded ngis::reports            1.0 [list source [file join $dir generic reports.tcl]]
package ifneeded ngis::entitymap          1.0 [list source [file join $dir generic map_entity_hash.tcl]]
#
package ifneeded dio::formatters          1.1 [list source [file join $dir generic formatters.tcl]]
package ifneeded DIO                      1.2.3 [list source [file join $dir generic dio.tcl]]
package ifneeded dio_Tdbc                 1.2.5 [list source [file join $dir generic dio_Tdbc.tcl]]


