package ifneeded ngis::procedures       0.2 [list source [file join $dir tcl procedures.tcl]]
package ifneeded ngis::msglogger        0.1 [list source [file join $dir tcl ngis_msglogger.tcl]]
package ifneeded termio                 1.1 [list source [file join $dir tcl termio.tcl]]
package ifneeded ngis::conf             1.1 [list source [file join $dir ngis_monitor_conf.tcl]]
package ifneeded ngis::job              1.1 [list source [file join $dir tcloo job.tcl]]
package ifneeded ngis::task             0.3 [list source [file join $dir tcl task.tcl]]
package ifneeded ngis::taskmessages     1.0 [list source [file join $dir tcl task_messages.tcl]]
package ifneeded ngis::servicedb        1.0 [list source [file join $dir tcl service_db.tcl]]
package ifneeded ngis::sequence         1.0 [list source [file join $dir tcloo sequence.tcl]]
package ifneeded ngis::jobcontroller    1.0 [list source [file join $dir tcloo job_controller.tcl]]
package ifneeded ngis::server           1.0 [list source [file join $dir tcloo server.tcl]]
package ifneeded ngis::client           1.0 [list source [file join $dir tcloo client.tcl]]
package ifneeded ngis::threads          1.0 [list source [file join $dir tcloo thread_master.tcl]]
package ifneeded ngis::hrformat         0.5 [list source [file join $dir tcloo hrformat.tcl]]
package ifneeded ngis::jsonformat       0.1 [list source [file join $dir tcloo jsonformat.tcl]]
package ifneeded ngis::common           1.0 [list source [file join $dir common.tcl]]
package ifneeded ngis::cli              0.1 [list source [file join $dir tcloo cli.tcl]]
package ifneeded ngis::utils            0.3 [list source [file join $dir utils snigutils.tcl]]
package ifneeded ngis::csprotomap       1.0 [list source [file join $dir tcl csprotomap.tcl]]
package ifneeded ngis::protocol         2.1 [list source [file join $dir tcloo client_server_protocol.tcl]]
package ifneeded ngis::clientio         1.0 [list source [file join $dir utils client_io.tcl]]
